version: "3.8"

services:
  script:
    image: esternit/task7bd:latest
    # build: ./script/
    ports:
      - "8000:8000"
    container_name: script-mtg
    depends_on:
      - db
    networks:
      - net
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db
    container_name: dbpg-mtg
    volumes:
      - ./database/postgres/data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
    ports:
      - "5432:5432"
    networks:
      - net

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - ./pgadmin-data:/var/lib/pgadmin
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - net
    restart: unless-stopped

  redis:
    image: redis:latest
    container_name: redis-mtg
    ports:
      - "6379:6379"
    networks:
      - net
    restart: unless-stopped

networks:
  net:
    driver: bridge
